### Lógica

Testes

In [29]:
import numpy as np
import pandas as pd

In [19]:
# operadores de comparação:
2 >= 3 # maior igual
'alfa' < 'beto' # ordem alfabética
2 != 5  # diferença
True == 1

True

### Operadores booleanos
and: recebe dois booleanos e retorna True se ambos forem True, False do contrário

or: recebe dois booleanos e retorna False se ambos forem False, True do contrário

not: retorna o contrário do que recebe

In [5]:
True and False

False

In [6]:
True or False

True

In [18]:
not True
not(True)

False

#### Para numpy array

Os operadores booleanos para numpy array são um pouco diferentes.

logical_and()

logical_or()

logical_not()

In [10]:
lista = [[1,2,3],
        [4,5,6]]
array = np.array(lista)

In [11]:
np.logical_and(array<5,array>2)

array([[False, False,  True],
       [ True, False, False]])

In [12]:
np.logical_or(array<5,array>2)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [13]:
np.logical_not(array<5,array>2)

array([[False, False, False],
       [False,  True,  True]])

In [16]:
# selecionando da numpy array
print(array[np.logical_and(array<5,array>2)]) # basta chamar a array e colocar dentro dos brackets o teste

[3 4]


### Condições e execução

In [24]:
z = 4
if z % 2 == 0:  # condição: "se o resto de z/2 é zero"
    print("z é par") # ação: "execute a expressão"
    # a identação indica a expressão dentro do if
else: # caso contrário
    print("z é impar")

z é par


In [27]:
z = 6
if z % 2 == 0:  # condição: "se o resto de z/2 é zero"
    print("z é divisivel por 2") # ação: "execute a expressão"
    # a identação indica a expressão dentro do if
elif z % 3 == 0: # outra condição
    print("z é divisivel por 3")
    
else: # caso contrário
    print("z não é divisivel por 2 nem por 3")

z é divisivel por 2


### Filtrando DataFrames

In [30]:
data = {'BR': {'country': 'Brazil', 'capital': 'Brasilia', 'area':8.516,'population': 200.40},
        'RU': {'country': 'Russia', 'capital': 'Moscow', 'area':17.100,'population': 143.50},
        'IN': {'country': 'India', 'capital': 'New Delhi', 'area':3.286,'population': 1252.00},
        'CH': {'country': "China", 'capital': 'Beijin', 'area':9.597,'population': 1357.00},
        'SA': {'country': 'South Africa', 'capital': 'Pretoria', 'area':1.221,'population': 52.98}}

brics = pd.DataFrame(data)
brics=brics.T
print(brics)

         country    capital   area population
BR        Brazil   Brasilia  8.516      200.4
RU        Russia     Moscow   17.1      143.5
IN         India  New Delhi  3.286       1252
CH         China     Beijin  9.597       1357
SA  South Africa   Pretoria  1.221      52.98


In [31]:
brics['area'] # Series

BR    8.516
RU     17.1
IN    3.286
CH    9.597
SA    1.221
Name: area, dtype: object

In [37]:
grandes = brics['area'] > 8 # serie de booleanos 
brics[grandes] # usando os booleanos pra indexar o dataframe
# ou
brics[brics['area'] > 8] # testa brics['area'] mas 'seleciona' a linha inteira

country   capital   area population
BR  Brazil  Brasilia  8.516      200.4
RU  Russia    Moscow   17.1      143.5
CH   China    Beijin  9.597       1357

In [39]:
# usando operador booleano
brics[np.logical_and(brics['area'] > 8,brics['area'] < 10)]

country   capital   area population
BR  Brazil  Brasilia  8.516      200.4
CH   China    Beijin  9.597       1357